# Delete these routes and define your own shop routes here

hubertinio_sylius_cashbill_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: Hubertinio\SyliusCashBillPlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

hubertinio_sylius_cashbill_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: Hubertinio\SyliusCashBillPlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
